#version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: proyecto_olap-postgres-1
    environment:
      POSTGRES_DB: restaurantes
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5-community
    container_name: proyecto_olap-neo4j-1
    environment:
      NEO4J_AUTH: neo4j/test1234
    ports:
      - "7474:7474"
      - "7687:7687"

  elasticsearch:
    image: elasticsearch:8.10.2
    container_name: proyecto_olap-elasticsearch-1
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  spark-master:
    image: apache/spark:3.5.3
    container_name: proyecto_olap-spark-master-1
    environment:
      - SPARK_MODE=master
    ports:
      - "8081:8080"
      - "7077:7077"

  spark-worker:
    image: apache/spark:3.5.3
    container_name: proyecto_olap-spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master

  hive-server:
    image: apache/hive:4.0.0
    container_name: proyecto_olap-hive-server-1
    ports:
      - "10000:10000"
    depends_on:
      - postgres

  metabase:
    image: metabase/metabase:latest
    container_name: proyecto_olap-metabase-1
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  airflow:
    build:
      context: .
      dockerfile: docker/airflow/Dockerfile
    container_name: proyecto_olap-airflow-1
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_DB=restaurantes
      - PG_USER=admin
      - PG_PASS=admin123
      - ES_URL=http://elasticsearch:9200
      - ES_INDEX=productos
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test1234
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./:/opt/airflow/proyecto_olap
    depends_on:
      - postgres
      - neo4j
      - elasticsearch
    command: airflow standalone


volumes:
  postgres_data:
