FROM node:18-alpine

WORKDIR /app

# Copiar dependencias
COPY restaurant-reservations/package*.json ./

# Instalar todas las dependencias (incluidas las de dev)
RUN npm install

# Copiar código fuente
COPY restaurant-reservations/src ./src
COPY restaurant-reservations/jest.config.js ./

# Copiar tests
COPY Tests ./tests

# Ejecutar tests
CMD ["npx", "jest", "--passWithNoTests"]

#Pruebas individuales
#docker run --rm restaurant-api:tests npx jest tests/auth.test.js --verbose
#docker run --rm restaurant-api:tests npx jest tests/menus.test.js --verbose
#docker run --rm restaurant-api:tests npx jest tests/orders.test.js --verbose
#docker run --rm restaurant-api:tests npx jest tests/reservations.test.js --verbose
#docker run --rm restaurant-api:tests npx jest tests/restaurants.test.js --verbose
